name: Run Python file
on:
  push:
    branches: [Dev]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pwd && pip install discord && pip install load_dotenv
       
    
    - name: Load environment variables
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "DISCORD_GUILD=${{ secrets.DISCORD_GUILD }}" >> .env

    
    - name: Run script
      run: python ./scripts/bot.py
